### ISSUE TITLE
代码搞起来，范爷

### ISSUE THREAD

**Issue by MartinChan3** [sjtuff/CurveGrindingCNC#1]
终于有Git信息了

**Comment by sjtuff** [comment]
2333，这个github要用什么git bash在电脑上建库什么的吗

**Comment by MartinChan3** [comment]
推荐gui客户端吧，不过范爷这种人比较适合Bash命令行操作，不然怎么体现水平 `https://desktop.github.com/`

**Comment by sjtuff** [comment]
放桌面的那个吗，我也下了，有点晕，我再摸索摸索 发自网易邮箱大师 在2017年09月01日 13:45，Martin Chan 写道： 推荐gui客户端吧，不过范爷这种人比较适合Bash命令行操作，不然怎么体现水平 https://desktop.github.com/ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
